// AUTO_GENERATED BY MVP Java Maven Plugin
package com.mvp.java.view.autogen;

import java.lang.Override;
import java.lang.String;

public enum FxmlEnum {
  TABPANE {
    @Override
    public String getFxmlFile() {
      return "/fxml/tabs/TabPane.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("tabpane.title");
    }
  },

  CONSOLETAB {
    @Override
    public String getFxmlFile() {
      return "/fxml/tabs/ConsoleTab.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("consoletab.title");
    }
  },

  RANDOM {
    @Override
    public String getFxmlFile() {
      return "/fxml/Random.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("random.title");
    }
  },

  LOGGERTAB {
    @Override
    public String getFxmlFile() {
      return "/fxml/tabs/LoggerTab.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("loggertab.title");
    }
  },

  LOGIN {
    @Override
    public String getFxmlFile() {
      return "/fxml/Login.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("login.title");
    }
  },

  MAIN {
    @Override
    public String getFxmlFile() {
      return "/fxml/Main.fxml";
    }

    @Override
    public String getTitle() {
      return getStringFromResourceBundle("main.title");
    }
  };

  public abstract String getFxmlFile();

  public abstract String getTitle();

  public String getStringFromResourceBundle(String key) {
    return java.util.ResourceBundle.getBundle("Bundle").getString(key);
  }
}
